apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
  namespace: k8-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: webapptask
          image: pritidevops/k8_app:latest
          ports:
            - containerPort: 8020


---

apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  namespace: k8-task
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 8020
      targetPort: 8020
      nodePort: 32000
  
